@extends('layouts.app')
@section('title', $isEdit?'Edit User':'New User')
@section('content')
<x-page-header :title="$isEdit?'Edit User':'New User'" :breadcrumbs="['Administration'=>null,'Users'=>route('users.index'),($isEdit?'Edit':'New')=>null]" />
<form method="POST" action="{{ $isEdit?route('users.update',$user):route('users.store') }}" id="user-form">@csrf @if($isEdit)@method('PUT')@endif
<div class="card"><div class="card-body row g-3">
<div class="col-md-4"><label class="form-label">Username <span class="required-mark">*</span></label><input name="username" class="form-control @error('username') is-invalid @enderror" value="{{ old('username',$user->username) }}" required>@error('username')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-4"><label class="form-label">Full Name <span class="required-mark">*</span></label><input name="name" class="form-control" value="{{ old('name',$user->name) }}" required></div>
<div class="col-md-4"><label class="form-label">Email <span class="required-mark">*</span></label><input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email',$user->email) }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-4"><label class="form-label">Contact Number</label><input name="contact_number" class="form-control" value="{{ old('contact_number',$user->contact_number) }}"></div>
<div class="col-md-4"><label class="form-label">Role <span class="required-mark">*</span></label><select name="role_id" id="role_id" class="form-select" required data-supplier-role-id="{{ $supplierRoleId }}">@foreach($roles as $r)<option value="{{ $r->id }}" @selected(old('role_id',$user->role_id)==$r->id)>{{ $r->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Status <span class="required-mark">*</span></label><select name="status" class="form-select">@foreach(\App\Enums\UserStatus::cases() as $s)<option value="{{ $s->value }}" @selected(old('status',$user->status?->value)===$s->value)>{{ $s->value }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Password {{ $isEdit?'(leave blank to keep)':'' }} @unless($isEdit)<span class="required-mark">*</span>@endunless</label><input type="password" name="password" class="form-control @error('password') is-invalid @enderror" {{ $isEdit?'':'required' }}>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-4"><label class="form-label">Confirm Password</label><input type="password" name="password_confirmation" class="form-control"></div>
<div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_super_admin" value="1" id="is_super_admin" @checked(old('is_super_admin', $user->is_super_admin))><label class="form-check-label" for="is_super_admin">Super Admin</label><div class="form-text">Super Admins can access all suppliers and sites in listings.</div></div></div>
<div class="col-12" id="supplier-section"><label class="form-label">Assigned Suppliers <span class="required-mark supplier-required-mark d-none">*</span></label><div class="row">@foreach($suppliers as $supplier)<div class="col-md-4"><div class="form-check"><input class="form-check-input supplier-checkbox" type="checkbox" name="supplier_ids[]" value="{{ $supplier->id }}" id="supplier_{{ $supplier->id }}" @checked(in_array($supplier->id, old('supplier_ids', $assignedSupplierIds)))><label class="form-check-label" for="supplier_{{ $supplier->id }}">{{ $supplier->supplier_name }}</label></div></div>@endforeach</div>@error('supplier_ids')<div class="text-danger small">{{ $message }}</div>@enderror</div>
<div class="col-12" id="sites-section"><label class="form-label">Assigned Sites <span class="required-mark sites-required-mark d-none">*</span></label><div class="row">@foreach($sites as $site)<div class="col-md-4"><div class="form-check"><input class="form-check-input site-checkbox" type="checkbox" name="site_ids[]" value="{{ $site->id }}" id="site_{{ $site->id }}" @checked(in_array($site->id, old('site_ids', $assignedSiteIds)))><label class="form-check-label" for="site_{{ $site->id }}">{{ $site->site_name }}</label></div></div>@endforeach</div>@error('site_ids')<div class="text-danger small">{{ $message }}</div>@enderror</div>
</div><div class="card-footer d-flex gap-2"><button class="btn btn-primary">{{ $isEdit?'Update':'Save' }}</button><a href="{{ route('users.index') }}" class="btn btn-secondary">Back</a></div></div></form>
@endsection
