<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{{ $title }}</title>
<style>body{font-family:DejaVu Sans,sans-serif;font-size:11px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:4px}th{background:#f0f0f0}.meta{margin-bottom:12px;font-size:10px;color:#555}</style>
</head>
<body>
<h2>{{ $title }}</h2>
<div class="meta">Generated by {{ $generatedBy }} on {{ $generatedAt }}</div>
<table><thead><tr>@foreach($columns as $col)<th>{{ $col }}</th>@endforeach</tr></thead>
<tbody>@foreach($rows as $row)<tr>@foreach($row as $cell)<td>{{ $cell }}</td>@endforeach</tr>@endforeach</tbody></table>
</body></html>
